#ifndef LORAWAN_CONF_H
#define LORAWAN_CONF_H

#ifndef LORAWAN_REGION
#define LORAWAN_REGION          LORAMAC_REGION_EU868
#endif

#ifndef LORAWAN_DEFAULT_CLASS
#define LORAWAN_DEFAULT_CLASS   CLASS_A
#endif

#ifndef LORAWAN_USE_OTAA
#define LORAWAN_USE_OTAA        1
#endif

#ifndef LORAWAN_DEFAULT_FPORT
#define LORAWAN_DEFAULT_FPORT   2
#endif

#ifndef LORAWAN_DEFAULT_CONFIRMED
#define LORAWAN_DEFAULT_CONFIRMED false
#endif

#ifndef LORAWAN_CLASSB_PINGSLOT_PERIODICITY
#define LORAWAN_CLASSB_PINGSLOT_PERIODICITY  3  // every 8s
#endif

#ifndef LORAWAN_MAX_TX_RETRIES
#define LORAWAN_MAX_TX_RETRIES  3
#endif

#ifndef LORAWAN_ADR_ENABLE
#define LORAWAN_ADR_ENABLE      true
#endif

#endif // LORAWAN_CONF_H
